"use strict";

const xs = [
"5D fractals",
"a debugger",
"a vector font renderer",
"a web scraper",
"anthropic",
"body idiom catalog",
"Buffy search",
"cellular automata",
"chinese idiom instruction",
"Eulerian paths",
"Facebook",
"friend fair travel planner",
"I Ching",
"Minesweeper",
"Misrosoft Powerpint",
"Open Telemetry",
"project idea generator",
"public Unix box",
"ray-traced audio",
"RCTV",
"replacement for SQL",
"silicone controllers",
"Stripe",
"text-based MUD",
"the service formerly known as Twitter",
"Uber",
];

const ys = [
"bears",
"cats",
"chess actions",
"dance partners",
"dogs",
"the Enterprise",
"LLMs",
"Nix users",
"prose/fiction",
"vampires",
"whale sharks",
];

const zs = [
"assembly",
"C",
"COBOL",
"Elixir",
"Gleam",
"Haskell",
"JavaScript",
"an LSP server",
"an MCP server",
"OCaml",
"PEGs",
"Python",
"a recursive CTE",
"vim script",
"Zig",
];

const bs = [
"a 6502",
"the blockchain",
"nix",
"an Nvidia H100",
"POSEVAC",
"the RapidRiter",
"a Raspberry Pi",
"the RCade",
"RCTV",
];

const cs = [
"and it's been golfed",
"at nuclear test sites",
"but e2e encrypted",
"but social",
"but *very* fast",
"but vibecoded",
"configured in Nix",
"solving the halting problem",
"via embeddings",
"with a swiping twist",
"with a IOT twist",
"with camera input",
"with extra AI",
"with phong shading",
];
